// GENERATED by core/detection/gen.mjs — DO NOT EDIT. Canonical: core/detection/.
// Unified framework / build-command / output / runtime detection (TypeScript).
//
// A faithful port of detect_core.py — SAME spec, SAME algorithm — kept in
// lockstep with it. PURE: a `Snapshot` in, a `BuildPlan` out, no `node:fs`,
// so it is safe to vendor into BOTH the CLI (Node) and the control-plane
// (browser). Each caller builds the Snapshot at its own fidelity (the CLI from
// the filesystem, drop-deploy from the dropped file tree).
//
// stdlib/spec only — vendored verbatim by gen.mjs into <consumer>/_detection/.
// The spec is emitted as a TS const (spec.ts) so there is no JSON-import-at-
// runtime friction under tsc + Node ESM. Edit core/detection/, rerun gen.mjs.
import { SPEC } from "./spec.js";

export interface PackageJson {
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

export interface Snapshot {
  packageJson: PackageJson | null;
  requirementsTxt: string | null;
  files: Set<string>;
  dirs: Set<string>;
  configTexts: Record<string, string>;
  hasHtml: boolean;
  layeroJson: Record<string, unknown> | null;
}

export interface BuildUnit {
  role: "static" | "frontend" | "backend";
  framework: string;
  root: string;
  packageManager: string | null;
  installCmd: string | null;
  buildCmd: string | null;
  outputDir: string | null;
  startCmd: string | null;
  runtimeKind: string | null;
  port: number | null;
}

export interface BuildPlan {
  projectKind: "static" | "spa" | "ssr" | "runtime" | "fullstack";
  framework: string;
  buildCmd: string | null;
  outputDir: string | null;
  packageManager: string;
  projectType: string;
  runtimeKind: string | null;
  units: BuildUnit[];
  apiPrefix: string | null;
  confident: boolean;
  label: string;
}

const CONFIG_EXTENSIONS = [".ts", ".mts", ".cts", ".js", ".mjs", ".cjs"];
const JS_COMMENT_RE = /\/\/[^\n]*|\/\*[\s\S]*?\*\//gm;
const NEXT_EXPORT_RE = /output\s*:\s*['"]export['"]/m;
const NEXT_DISTDIR_RE = /distDir\s*:\s*['"]([^'"]+)['"]/m;
const OUTPUT_KEY_RE = /\b(?:outDir|distDir|output_dir)\s*[:=]\s*['"]([^'"]+)['"]/;
const NEXT_CONFIG_NAMES = ["next.config.mjs", "next.config.ts", "next.config.js", "next.config.cjs"];

type FW = Record<string, any>;

function hasDep(pkg: PackageJson | null, name: string): boolean {
  if (!pkg) return false;
  return Boolean((pkg.dependencies ?? {})[name] ?? (pkg.devDependencies ?? {})[name]);
}

function scriptsOf(pkg: PackageJson | null): Record<string, string> {
  return (pkg?.scripts && typeof pkg.scripts === "object") ? pkg.scripts : {};
}

export function detectPackageManager(files: Set<string>): any {
  const pm = SPEC.package_managers;
  for (const name of pm.order) {
    const mgr = pm.managers[name];
    if (mgr.lockfiles.some((lf: string) => files.has(lf))) return { name, ...mgr, hasLock: true };
  }
  return { name: "npm", ...pm.managers.npm, hasLock: false };
}

function configBasenamePresent(snap: Snapshot, basename: string): boolean {
  return CONFIG_EXTENSIONS.some((ext) => snap.files.has(basename + ext));
}

function frameworkMatches(fw: FW, snap: Snapshot): boolean {
  const sig = fw.signals;
  const pkg = snap.packageJson;
  if (sig.always) return true;
  for (const dep of sig.deps ?? []) if (hasDep(pkg, dep)) return true;
  for (const cf of sig.config_files ?? []) if (snap.files.has(cf)) return true;
  if (sig.config_basename && configBasenamePresent(snap, sig.config_basename)) return true;
  for (const name of sig.script_names ?? []) if (name in scriptsOf(pkg)) return true;
  for (const sub of sig.script_contains ?? []) {
    if (Object.values(scriptsOf(pkg)).some((v) => typeof v === "string" && v.includes(sub))) return true;
  }
  for (const d of sig.dir_markers ?? []) if (snap.dirs.has(d)) return true;
  if (sig.config_tokens) {
    for (const cf of sig.config_token_files ?? []) {
      if (snap.files.has(cf)) {
        const text = snap.configTexts[cf] ?? "";
        if ((sig.config_tokens as string[]).some((tok) => text.includes(tok))) return true;
      }
    }
  }
  if (sig.html_when_no_spa_deps) {
    if (pkg !== null && (sig.spa_hint_deps ?? []).some((d: string) => hasDep(pkg, d))) return false;
    return snap.hasHtml;
  }
  return false;
}

const stripJsComments = (t: string): string => t.replace(JS_COMMENT_RE, "");

export function nextConfigStaticExport(text: string | null): boolean | null {
  if (text === null || text === undefined) return null;
  return NEXT_EXPORT_RE.test(stripJsComments(text));
}

function extractOutkey(text: string | null | undefined): string | null {
  if (!text) return null;
  const m = OUTPUT_KEY_RE.exec(text);
  if (!m) return null;
  let val = m[1]!.trim();
  if (val.startsWith("./")) val = val.slice(2);
  return val || null;
}

function extractNextDistdir(text: string | null | undefined): string | null {
  if (!text) return null;
  const m = NEXT_DISTDIR_RE.exec(stripJsComments(text));
  return m ? m[1]! : null;
}

export function angularOutputDir(text: string | null | undefined): string | null {
  if (!text) return null;
  let cfg: any;
  try {
    cfg = JSON.parse(text);
  } catch {
    return null;
  }
  if (!cfg || typeof cfg !== "object") return null;
  const projects = cfg.projects;
  if (!projects || typeof projects !== "object") return null;
  const names = Object.keys(projects);
  if (!names.length) return null;
  const def = cfg.defaultProject;
  const name = def && projects[def] ? def : names[0]!;
  const buildCfg = projects[name]?.architect?.build;
  if (!buildCfg || typeof buildCfg !== "object") return null;
  const opts = buildCfg.options ?? {};
  const raw = typeof opts === "object" && opts ? opts.outputPath : undefined;
  let out = typeof raw === "string" && raw.trim() ? raw.trim() : `dist/${name}`;
  if (out.startsWith("./")) out = out.slice(2);
  const builder = typeof buildCfg.builder === "string" ? buildCfg.builder : "";
  return builder.endsWith(":application") ? `${out}/browser` : out;
}

function nextConfigName(snap: Snapshot): string {
  for (const n of NEXT_CONFIG_NAMES) if (n in snap.configTexts || snap.files.has(n)) return n;
  return NEXT_CONFIG_NAMES[0]!;
}

function configTextForBasename(snap: Snapshot, basename: string): string | null {
  for (const ext of CONFIG_EXTENSIONS) {
    const t = snap.configTexts[basename + ext];
    if (t !== undefined) return t;
  }
  return null;
}

function resolveOutputDir(fw: FW, snap: Snapshot): string {
  const out = fw.output_dir;
  const def = out.default as string;
  switch (out.extract) {
    case "next_distdir":
      return extractNextDistdir(snap.configTexts[nextConfigName(snap)]) ?? def;
    case "outkey":
      return extractOutkey(configTextForBasename(snap, out.extract_config_basename ?? "")) ?? def;
    case "angular":
      return angularOutputDir(snap.configTexts["angular.json"]) ?? def;
    case "vitepress_docs":
      return [...snap.files].some((f) => f.startsWith("docs/.vitepress/config")) ? "docs/.vitepress/dist" : def;
    default:
      return def;
  }
}

function resolveBuildCmd(fw: FW, snap: Snapshot, pmRun: string): string | null {
  const build = fw.build;
  if (build.no_build) return null;
  const scripts = scriptsOf(snap.packageJson);
  for (const entry of build.scripts ?? []) {
    const val = scripts[entry.name];
    if (typeof val !== "string" || !val.trim()) continue;
    if (entry.contains && !val.includes(entry.contains)) continue;
    return `${pmRun} ${entry.name}`;
  }
  const fallback = build.fallback;
  if (!fallback) return null;
  return build.npx === false ? fallback : `npx ${fallback}`;
}

function sortedFrameworks(): FW[] {
  return [...SPEC.frameworks].sort((a: FW, b: FW) => a.order - b.order);
}

function matchFramework(snap: Snapshot): FW {
  for (const fw of sortedFrameworks()) if (frameworkMatches(fw, snap)) return fw;
  return SPEC.frameworks.find((f: FW) => f.name === "generic");
}

function frameworkByName(name: string | null | undefined): FW | null {
  const n = (name ?? "").trim().toLowerCase();
  if (!n) return null;
  for (const fw of SPEC.frameworks) if (fw.name === n || (fw.aliases ?? []).includes(n)) return fw;
  return null;
}

function staticUnit(pm: any): BuildUnit {
  return {
    role: "static", framework: "static", root: "", packageManager: pm.name,
    installCmd: null, buildCmd: null, outputDir: ".", startCmd: null, runtimeKind: null, port: null,
  };
}

function spaUnit(fw: FW, snap: Snapshot, pm: any): BuildUnit {
  return {
    role: "static", framework: fw.name, root: "", packageManager: pm.name,
    installCmd: fw.skip_install ? null : pm.install,
    buildCmd: resolveBuildCmd(fw, snap, pm.run),
    outputDir: resolveOutputDir(fw, snap),
    startCmd: null, runtimeKind: null, port: null,
  };
}

export function detectFramework(snap: Snapshot, frameworkHint?: string | null): [BuildUnit, string | null] {
  const pm = detectPackageManager(snap.files);
  let unknown: string | null = null;
  let fw: FW | null = null;
  if (frameworkHint) {
    fw = frameworkByName(frameworkHint);
    if (fw === null) unknown = frameworkHint;
  }
  if (fw === null) fw = matchFramework(snap);
  if (fw.name === "static") return [staticUnit(pm), unknown];
  return [spaUnit(fw, snap, pm), unknown];
}

export function detectRuntime(snap: Snapshot): string | null {
  const rt = SPEC.runtime;
  const pkg = snap.packageJson;
  if (hasDep(pkg, "next")) {
    const text = snap.configTexts[nextConfigName(snap)];
    if (nextConfigStaticExport(text ?? null) === false) return "ssr_next";
  }
  if (pkg && rt.node_web_signals.some((d: string) => hasDep(pkg, d)) &&
      !rt.node_frontend_deps.some((d: string) => hasDep(pkg, d))) {
    return "node_web";
  }
  const reqs = (snap.requirementsTxt ?? "").toLowerCase();
  if (reqs) {
    const hasEntry = rt.python_entrypoints.some((f: string) => snap.files.has(f));
    if (reqs.includes("streamlit") && snap.files.has("app.py")) return "streamlit";
    if (reqs.includes("gradio") && snap.files.has("app.py")) return "gradio";
    if (hasEntry && rt.py_web_signals.some((s: string) => reqs.includes(s))) return "python_web";
  }
  return null;
}

function runtimeFromLayero(layero: Record<string, unknown> | null): [string, Record<string, unknown>] | null {
  if (!layero || typeof layero !== "object") return null;
  const rt = SPEC.runtime;
  const aliases = rt.layero_runtime_aliases as Record<string, string>;
  let kind = layero.runtime as string | undefined;
  if (typeof kind === "string") {
    kind = aliases[kind] ?? kind;
    if (kind in rt.kinds) return [kind, layero];
  }
  const fe = layero.frontend, be = layero.backend;
  if (fe && typeof fe === "object" && be && typeof be === "object") {
    let beKind = (be as any).runtime as string | undefined;
    if (typeof beKind === "string") {
      beKind = aliases[beKind] ?? beKind;
      if (["python_web", "node_web", "ssr_next"].includes(beKind)) return [`__fullstack__:${beKind}`, layero];
    }
  }
  return null;
}

const PY_FRAMEWORK_ORDER: [string, string][] = [
  ["django", "django"], ["fastapi", "fastapi"], ["flask", "flask"], ["litestar", "litestar"],
  ["starlite", "litestar"], ["quart", "quart"], ["sanic", "sanic"], ["blacksheep", "blacksheep"],
  ["falcon", "falcon"], ["bottle", "bottle"], ["pyramid", "pyramid"], ["aiohttp", "aiohttp"],
  ["tornado", "tornado"], ["starlette", "starlette"],
];
const NODE_FRAMEWORK_ORDER: [string, string][] = [
  ["@nestjs/core", "nestjs"], ["@adonisjs/core", "adonis"], ["fastify", "fastify"],
  ["@hapi/hapi", "hapi"], ["hapi", "hapi"], ["koa", "koa"], ["hono", "hono"],
  ["restify", "restify"], ["express", "express"],
];

export function detectRuntimeFramework(snap: Snapshot): string | null {
  const reqs = (snap.requirementsTxt ?? "").toLowerCase();
  if (reqs) for (const [token, name] of PY_FRAMEWORK_ORDER) if (reqs.includes(token)) return name;
  if (snap.packageJson) for (const [dep, name] of NODE_FRAMEWORK_ORDER) if (hasDep(snap.packageJson, dep)) return name;
  return null;
}

function runtimePlan(snap: Snapshot, pm: any, projectType: string): BuildPlan {
  const meta = SPEC.runtime.kinds[projectType];
  const framework = detectRuntimeFramework(snap) ?? projectType;
  const unit: BuildUnit = {
    role: "backend", framework, root: "",
    packageManager: snap.packageJson ? pm.name : null,
    installCmd: null, buildCmd: null, outputDir: null,
    startCmd: null, runtimeKind: meta.runtime_kind, port: meta.port,
  };
  return {
    projectKind: projectType === "ssr_next" ? "ssr" : "runtime",
    framework, buildCmd: null, outputDir: null, packageManager: pm.name,
    projectType, runtimeKind: meta.runtime_kind, units: [unit],
    apiPrefix: null, confident: true, label: projectType,
  };
}

function fullstackPlan(_snap: Snapshot, pm: any, layero: Record<string, unknown>, beProjectType: string): BuildPlan {
  const meta = SPEC.runtime.kinds[beProjectType];
  const fe = (layero.frontend ?? {}) as any;
  const be = (layero.backend ?? {}) as any;
  const apiPrefix = String(layero.api_prefix ?? "/api").trim() || "/api";
  const feUnit: BuildUnit = {
    role: "frontend", framework: String(fe.framework ?? "generic"),
    root: String(fe.root ?? "").replace(/^\/+|\/+$/g, ""),
    packageManager: null, installCmd: null,
    buildCmd: fe.build ? String(fe.build) : null,
    outputDir: String(fe.output ?? "dist").replace(/^\/+|\/+$/g, ""),
    startCmd: null, runtimeKind: null, port: null,
  };
  const beUnit: BuildUnit = {
    role: "backend", framework: beProjectType,
    root: String(be.root ?? "").replace(/^\/+|\/+$/g, ""),
    packageManager: null, installCmd: null, buildCmd: null, outputDir: null,
    startCmd: be.start ? String(be.start) : null,
    runtimeKind: meta.runtime_kind, port: Number(be.port ?? meta.port),
  };
  return {
    projectKind: "fullstack", framework: beProjectType, buildCmd: null, outputDir: null,
    packageManager: pm.name, projectType: beProjectType, runtimeKind: meta.runtime_kind,
    units: [feUnit, beUnit], apiPrefix, confident: true, label: "Fullstack",
  };
}

export function detect(snap: Snapshot, frameworkHint?: string | null): BuildPlan {
  const pm = detectPackageManager(snap.files);

  const lj = runtimeFromLayero(snap.layeroJson);
  if (lj !== null) {
    const [kind, layero] = lj;
    if (kind.startsWith("__fullstack__:")) return fullstackPlan(snap, pm, layero, kind.split(":")[1]!);
    return runtimePlan(snap, pm, kind);
  }

  const rkind = detectRuntime(snap);
  if (rkind !== null) return runtimePlan(snap, pm, rkind);

  let fw: FW | null = frameworkHint ? frameworkByName(frameworkHint) : null;
  if (fw === null) fw = matchFramework(snap);

  let unit: BuildUnit;
  let kind: BuildPlan["projectKind"];
  let confident: boolean;
  if (fw.name === "static") {
    unit = staticUnit(pm);
    kind = "static";
    confident = snap.hasHtml;
  } else {
    unit = spaUnit(fw, snap, pm);
    kind = "spa";
    confident = fw.name !== "generic";
  }
  return {
    projectKind: kind, framework: fw.name, buildCmd: unit.buildCmd, outputDir: unit.outputDir,
    packageManager: pm.name, projectType: "spa", runtimeKind: null, units: [unit],
    apiPrefix: null, confident, label: fw.label,
  };
}

/** Build a Snapshot from already-read inputs (caller does the IO). */
export function snapshotFromInputs(opts: {
  packageJson?: PackageJson | null;
  requirementsTxt?: string | null;
  files?: Iterable<string>;
  dirs?: Iterable<string>;
  configTexts?: Record<string, string>;
  layeroJson?: Record<string, unknown> | null;
  hasHtml?: boolean;
}): Snapshot {
  const files = new Set(opts.files ?? []);
  const hasHtml = opts.hasHtml ?? [...files].some((f) => f.endsWith(".html") || f.endsWith(".htm"));
  return {
    packageJson: opts.packageJson ?? null,
    requirementsTxt: opts.requirementsTxt ?? null,
    files,
    dirs: new Set(opts.dirs ?? []),
    configTexts: opts.configTexts ?? {},
    hasHtml,
    layeroJson: opts.layeroJson ?? null,
  };
}

// Config files whose CONTENT the detector reads (for the caller's snapshot builder).
export const CONFIG_TEXT_FILES = [
  ...NEXT_CONFIG_NAMES, "angular.json", "config.toml", "config.yaml", "config.json",
];
export const CONFIG_TEXT_BASENAMES = ["vite.config", "astro.config"];
export { CONFIG_EXTENSIONS };
